### PR TITLE
Output error, ignore .idea, rm unused variable

### PR DESCRIPTION
**Pull request by eagleeye**
now in case of uncaught it shows

```
  2) jscs should pass for server:
     Uncaught No configuration found. Add a .jscsrc file to your project root or use the -c option.
```

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks for the contribution. I've merged #2 so that `execFile` is no longer needed.

BTW, what's `.idea` file for?

**Comment by tomchentw** [comment]
Released [v1.1.0](https://github.com/tomchentw/mocha-jscs/releases/tag/v1.1.0).

**Comment by eagleeye** [comment]
`.idea` is for all Intelij Idea based IDEs, like [WebStorm](https://www.jetbrains.com/webstorm/) (super popular IDE for js), [PHPStorm](https://www.jetbrains.com/phpstorm/), Idea, PyCharm and others

**Comment by tomchentw** [comment]
Got it. I copy the template from https://www.gitignore.io/ so it might be a good place to update this, too!

**Pull request closed without merging**
