### PR TITLE
publish only needed files

### PR DESCRIPTION
**Pull request by eagleeye**
Only package.json, README.md, LICENSE,CHANGELOG and lib are really needed. Specifying the "files" key in package.json will limit these files for publishing without .npmignore
https://docs.npmjs.com/files/package.json#files
currently all files are published
image
after publishing new version of this package with this PR it will look similar to this:
image
+Changelog

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks @eagleeye . In other projects I use `files` as well.

Could you kindly add `"CHANGELOG.md"` to `files` array? Then I can merge this. Thanks!

**Comment by eagleeye** [comment]
@tomchentw no need for that https://docs.npmjs.com/files/package.json#files

> Certain files are always included, regardless of settings:
> 
> package.json
> README (and its variants)
> **> CHANGELOG (and its variants)**
> LICENSE / LICENCE

**Comment by tomchentw** [comment]
@eagleeye you're awesome! I didn't notice that before. Thanks!!!!

**Comment by tomchentw** [comment]
Published [v4.2.1](https://github.com/tomchentw/mocha-jscs/releases/tag/v4.2.1)

**Pull request merged**
