### PR TITLE
Update jscs dependency

### PR DESCRIPTION
**Pull request by mohsen1**
Please release this in a major version

### CODE REVIEW

**Comment by mohsen1** [comment]
Fixes #7

**Comment by tomchentw** [comment]
Of course major version totally make sense. Thanks for the fix.

**Comment by tomchentw** [comment]
Closed by ff1743a

**Comment by tomchentw** [comment]
Released [v2.0.0](https://github.com/tomchentw/mocha-jscs/releases/tag/v2.0.0)

**Comment by mohsen1** [comment]
👍

**Pull request closed without merging**
